//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace DocsGen;

interface

uses
    System;
    
type
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute('System.Resources.Tools.StronglyTypedResourceBuilder', '4.0.0.0')]
    [System.Diagnostics.DebuggerNonUserCodeAttribute]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    Resources = class
    private 
        class var resourceMan: System.Resources.ResourceManager;
        class var resourceCulture: System.Globalization.CultureInfo;
        class method get_ResourceManager: System.Resources.ResourceManager;
        class method get_Culture: System.Globalization.CultureInfo;
        class method set_Culture(value: System.Globalization.CultureInfo);
        class method get_AssignTagSyntaxException: System.String;
        class method get_BlankFileSystemDoesNotAllowIncludesException: System.String;
        class method get_BlockTagAlreadyDefinedException: System.String;
        class method get_BlockTagNoElseException: System.String;
        class method get_BlockTagNoEndException: System.String;
        class method get_BlockTagNotClosedException: System.String;
        class method get_BlockTagNotTerminatedException: System.String;
        class method get_BlockTagSyntaxException: System.String;
        class method get_BlockUnknownTagException: System.String;
        class method get_BlockVariableNotTerminatedException: System.String;
        class method get_CapureTagSyntaxException: System.String;
        class method get_CaseTagElseSyntaxException: System.String;
        class method get_CaseTagSyntaxException: System.String;
        class method get_CaseTagWhenSyntaxException: System.String;
        class method get_ConditionUnknownOperatorException: System.String;
        class method get_ContextLiquidError: System.String;
        class method get_ContextLiquidSyntaxError: System.String;
        class method get_ContextObjectInvalidException: System.String;
        class method get_ContextStackException: System.String;
        class method get_CycleTagSyntaxException: System.String;
        class method get_DropWrongNamingConventionMessage: System.String;
        class method get_ExtendsTagCanBeUsedOneException: System.String;
        class method get_ExtendsTagMustBeFirstTagException: System.String;
        class method get_ExtendsTagSyntaxException: System.String;
        class method get_ExtendsTagUnallowedTagsException: System.String;
        class method get_ForTagSyntaxException: System.String;
        class method get_IfTagSyntaxException: System.String;
        class method get_IncludeTagSyntaxException: System.String;
        class method get_LocalFileSystemIllegalTemplateNameException: System.String;
        class method get_LocalFileSystemIllegalTemplatePathException: System.String;
        class method get_LocalFileSystemTemplateNotFoundException: System.String;
        class method get_StrainerFilterHasNoValueException: System.String;
        class method get_TableRowTagSyntaxException: System.String;
        class method get_VariableFilterNotFoundException: System.String;
        class method get_WeakTableKeyNotFoundException: System.String;
    assembly 
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property ResourceManager: System.Resources.ResourceManager read get_ResourceManager;
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property Culture: System.Globalization.CultureInfo read get_Culture write set_Culture;
        class property AssignTagSyntaxException: System.String read get_AssignTagSyntaxException;
        class property BlankFileSystemDoesNotAllowIncludesException: System.String read get_BlankFileSystemDoesNotAllowIncludesException;
        class property BlockTagAlreadyDefinedException: System.String read get_BlockTagAlreadyDefinedException;
        class property BlockTagNoElseException: System.String read get_BlockTagNoElseException;
        class property BlockTagNoEndException: System.String read get_BlockTagNoEndException;
        class property BlockTagNotClosedException: System.String read get_BlockTagNotClosedException;
        class property BlockTagNotTerminatedException: System.String read get_BlockTagNotTerminatedException;
        class property BlockTagSyntaxException: System.String read get_BlockTagSyntaxException;
        class property BlockUnknownTagException: System.String read get_BlockUnknownTagException;
        class property BlockVariableNotTerminatedException: System.String read get_BlockVariableNotTerminatedException;
        class property CapureTagSyntaxException: System.String read get_CapureTagSyntaxException;
        class property CaseTagElseSyntaxException: System.String read get_CaseTagElseSyntaxException;
        class property CaseTagSyntaxException: System.String read get_CaseTagSyntaxException;
        class property CaseTagWhenSyntaxException: System.String read get_CaseTagWhenSyntaxException;
        class property ConditionUnknownOperatorException: System.String read get_ConditionUnknownOperatorException;
        class property ContextLiquidError: System.String read get_ContextLiquidError;
        class property ContextLiquidSyntaxError: System.String read get_ContextLiquidSyntaxError;
        class property ContextObjectInvalidException: System.String read get_ContextObjectInvalidException;
        class property ContextStackException: System.String read get_ContextStackException;
        class property CycleTagSyntaxException: System.String read get_CycleTagSyntaxException;
        class property DropWrongNamingConventionMessage: System.String read get_DropWrongNamingConventionMessage;
        class property ExtendsTagCanBeUsedOneException: System.String read get_ExtendsTagCanBeUsedOneException;
        class property ExtendsTagMustBeFirstTagException: System.String read get_ExtendsTagMustBeFirstTagException;
        class property ExtendsTagSyntaxException: System.String read get_ExtendsTagSyntaxException;
        class property ExtendsTagUnallowedTagsException: System.String read get_ExtendsTagUnallowedTagsException;
        class property ForTagSyntaxException: System.String read get_ForTagSyntaxException;
        class property IfTagSyntaxException: System.String read get_IfTagSyntaxException;
        class property IncludeTagSyntaxException: System.String read get_IncludeTagSyntaxException;
        class property LocalFileSystemIllegalTemplateNameException: System.String read get_LocalFileSystemIllegalTemplateNameException;
        class property LocalFileSystemIllegalTemplatePathException: System.String read get_LocalFileSystemIllegalTemplatePathException;
        class property LocalFileSystemTemplateNotFoundException: System.String read get_LocalFileSystemTemplateNotFoundException;
        class property StrainerFilterHasNoValueException: System.String read get_StrainerFilterHasNoValueException;
        class property TableRowTagSyntaxException: System.String read get_TableRowTagSyntaxException;
        class property VariableFilterNotFoundException: System.String read get_VariableFilterNotFoundException;
        class property WeakTableKeyNotFoundException: System.String read get_WeakTableKeyNotFoundException;
    assembly 
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('Microsoft.Performance', 'CA1811:AvoidUncalledPrivateCode')]
        constructor;
    end;
    
implementation

{ Resources }

constructor Resources;
begin
end;

class method Resources.get_ResourceManager: System.Resources.ResourceManager;
begin
    if System.Object.ReferenceEquals(resourceMan, nil) then begin
        var temp: System.Resources.ResourceManager := new System.Resources.ResourceManager('DocsGen.Resources', typeOf(Resources).Assembly);
        resourceMan := temp;
    end;
    exit(resourceMan);
end;

class method Resources.get_Culture: System.Globalization.CultureInfo;
begin
    exit(resourceCulture);
end;

class method Resources.set_Culture(value: System.Globalization.CultureInfo);
begin
    resourceCulture := value;
end;

class method Resources.get_AssignTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('AssignTagSyntaxException', resourceCulture));
end;

class method Resources.get_BlankFileSystemDoesNotAllowIncludesException: System.String;
begin
    exit(ResourceManager.GetString('BlankFileSystemDoesNotAllowIncludesException', resourceCulture));
end;

class method Resources.get_BlockTagAlreadyDefinedException: System.String;
begin
    exit(ResourceManager.GetString('BlockTagAlreadyDefinedException', resourceCulture));
end;

class method Resources.get_BlockTagNoElseException: System.String;
begin
    exit(ResourceManager.GetString('BlockTagNoElseException', resourceCulture));
end;

class method Resources.get_BlockTagNoEndException: System.String;
begin
    exit(ResourceManager.GetString('BlockTagNoEndException', resourceCulture));
end;

class method Resources.get_BlockTagNotClosedException: System.String;
begin
    exit(ResourceManager.GetString('BlockTagNotClosedException', resourceCulture));
end;

class method Resources.get_BlockTagNotTerminatedException: System.String;
begin
    exit(ResourceManager.GetString('BlockTagNotTerminatedException', resourceCulture));
end;

class method Resources.get_BlockTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('BlockTagSyntaxException', resourceCulture));
end;

class method Resources.get_BlockUnknownTagException: System.String;
begin
    exit(ResourceManager.GetString('BlockUnknownTagException', resourceCulture));
end;

class method Resources.get_BlockVariableNotTerminatedException: System.String;
begin
    exit(ResourceManager.GetString('BlockVariableNotTerminatedException', resourceCulture));
end;

class method Resources.get_CapureTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('CapureTagSyntaxException', resourceCulture));
end;

class method Resources.get_CaseTagElseSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('CaseTagElseSyntaxException', resourceCulture));
end;

class method Resources.get_CaseTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('CaseTagSyntaxException', resourceCulture));
end;

class method Resources.get_CaseTagWhenSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('CaseTagWhenSyntaxException', resourceCulture));
end;

class method Resources.get_ConditionUnknownOperatorException: System.String;
begin
    exit(ResourceManager.GetString('ConditionUnknownOperatorException', resourceCulture));
end;

class method Resources.get_ContextLiquidError: System.String;
begin
    exit(ResourceManager.GetString('ContextLiquidError', resourceCulture));
end;

class method Resources.get_ContextLiquidSyntaxError: System.String;
begin
    exit(ResourceManager.GetString('ContextLiquidSyntaxError', resourceCulture));
end;

class method Resources.get_ContextObjectInvalidException: System.String;
begin
    exit(ResourceManager.GetString('ContextObjectInvalidException', resourceCulture));
end;

class method Resources.get_ContextStackException: System.String;
begin
    exit(ResourceManager.GetString('ContextStackException', resourceCulture));
end;

class method Resources.get_CycleTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('CycleTagSyntaxException', resourceCulture));
end;

class method Resources.get_DropWrongNamingConventionMessage: System.String;
begin
    exit(ResourceManager.GetString('DropWrongNamingConventionMessage', resourceCulture));
end;

class method Resources.get_ExtendsTagCanBeUsedOneException: System.String;
begin
    exit(ResourceManager.GetString('ExtendsTagCanBeUsedOneException', resourceCulture));
end;

class method Resources.get_ExtendsTagMustBeFirstTagException: System.String;
begin
    exit(ResourceManager.GetString('ExtendsTagMustBeFirstTagException', resourceCulture));
end;

class method Resources.get_ExtendsTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('ExtendsTagSyntaxException', resourceCulture));
end;

class method Resources.get_ExtendsTagUnallowedTagsException: System.String;
begin
    exit(ResourceManager.GetString('ExtendsTagUnallowedTagsException', resourceCulture));
end;

class method Resources.get_ForTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('ForTagSyntaxException', resourceCulture));
end;

class method Resources.get_IfTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('IfTagSyntaxException', resourceCulture));
end;

class method Resources.get_IncludeTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('IncludeTagSyntaxException', resourceCulture));
end;

class method Resources.get_LocalFileSystemIllegalTemplateNameException: System.String;
begin
    exit(ResourceManager.GetString('LocalFileSystemIllegalTemplateNameException', resourceCulture));
end;

class method Resources.get_LocalFileSystemIllegalTemplatePathException: System.String;
begin
    exit(ResourceManager.GetString('LocalFileSystemIllegalTemplatePathException', resourceCulture));
end;

class method Resources.get_LocalFileSystemTemplateNotFoundException: System.String;
begin
    exit(ResourceManager.GetString('LocalFileSystemTemplateNotFoundException', resourceCulture));
end;

class method Resources.get_StrainerFilterHasNoValueException: System.String;
begin
    exit(ResourceManager.GetString('StrainerFilterHasNoValueException', resourceCulture));
end;

class method Resources.get_TableRowTagSyntaxException: System.String;
begin
    exit(ResourceManager.GetString('TableRowTagSyntaxException', resourceCulture));
end;

class method Resources.get_VariableFilterNotFoundException: System.String;
begin
    exit(ResourceManager.GetString('VariableFilterNotFoundException', resourceCulture));
end;

class method Resources.get_WeakTableKeyNotFoundException: System.String;
begin
    exit(ResourceManager.GetString('WeakTableKeyNotFoundException', resourceCulture));
end;

end.
